# fly.toml app configuration file generated for address-balance on 2023-10-19T14:46:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "address-balance"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
