openapi: 3.0.3
info:
  title: balance API
  version: 1.0.0
  contact: {}
servers:
- url: '{{url}}'
paths:
  /api/balances:
    get:
      summary: get balances
      description: get balances
      operationId: getBalances
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                addresses:
                  type: array
                  items:
                    type: string
                    example: james.eth
                  example:
                  - james.eth
                  - kevin.eth
                  - sam.eth
                  - keneth
                  - '455656'
                  - 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045
                  - vitalik.eth
                  - 0x4687466ac9bD165cA3bF2F6b6446822560b9fC3d
                  - michael.eth
                  - '12'
            examples:
              get balances:
                value:
                  addresses:
                  - james.eth
                  - kevin.eth
                  - sam.eth
                  - keneth
                  - '455656'
                  - 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045
                  - vitalik.eth
                  - 0x4687466ac9bD165cA3bF2F6b6446822560b9fC3d
                  - michael.eth
                  - '12'
      responses:
        '200':
          description: get balances
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Connection:
              schema:
                type: string
                example: keep-alive
            Content-Length:
              schema:
                type: string
                example: '320'
            Content-Security-Policy:
              schema:
                type: string
                example: 'default-src ''self'';base-uri ''self'';font-src ''self'' https: data:;form-action ''self'';frame-ancestors ''self'';img-src ''self'' data:;object-src ''none'';script-src ''self'';script-src-attr ''none'';style-src ''self'' https: ''unsafe-inline'';upgrade-insecure-requests'
            Cross-Origin-Opener-Policy:
              schema:
                type: string
                example: same-origin
            Cross-Origin-Resource-Policy:
              schema:
                type: string
                example: same-origin
            Date:
              schema:
                type: string
                example: Wed, 18 Oct 2023 12:31:21 GMT
            ETag:
              schema:
                type: string
                example: W/"140-Ta6WGYe0hZY9nfeb0DrtR+lNp+k"
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
            Origin-Agent-Cluster:
              schema:
                type: string
                example: ?1
            Referrer-Policy:
              schema:
                type: string
                example: no-referrer
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=15552000; includeSubDomains
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-DNS-Prefetch-Control:
              schema:
                type: string
                example: off
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            X-XSS-Protection:
              schema:
                type: string
                example: '0'
          content:
            application/json:
              schema:
                type: object
                properties:
                  0x4687466ac9bD165cA3bF2F6b6446822560b9fC3d:
                    type: string
                    example: '18.8519'
                  0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045:
                    type: string
                    example: '935.143'
                  12-is-an-invalid-address:
                    type: string
                    example: '0'
                  455656-is-an-invalid-address:
                    type: string
                    example: '0'
                  james.eth:
                    type: string
                    example: '1.543'
                  keneth-is-an-invalid-address:
                    type: string
                    example: '0'
                  kevin.eth:
                    type: string
                    example: '0.7371'
                  michael.eth:
                    type: string
                    example: '18.8519'
                  sam.eth:
                    type: string
                    example: '0.0084'
                  vitalik.eth:
                    type: string
                    example: '935.143'
              examples:
                get balances:
                  value:
                    0x4687466ac9bD165cA3bF2F6b6446822560b9fC3d: '18.8519'
                    0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045: '935.143'
                    12-is-an-invalid-address: '0'
                    455656-is-an-invalid-address: '0'
                    james.eth: '1.543'
                    keneth-is-an-invalid-address: '0'
                    kevin.eth: '0.7371'
                    michael.eth: '18.8519'
                    sam.eth: '0.0084'
                    vitalik.eth: '935.143'
tags: []

